# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-30 10:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('subtotal', models.DecimalField(decimal_places=3, default=0.0, max_digits=10)),
                ('total', models.DecimalField(decimal_places=3, default=0.0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_entry', models.DateTimeField()),
                ('date_departure', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('features', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('size', models.DecimalField(decimal_places=3, default=0.0, max_digits=10)),
                ('price', models.DecimalField(decimal_places=3, default=0.0, max_digits=10)),
                ('image', models.ImageField(upload_to=b'')),
            ],
        ),
        migrations.AddField(
            model_name='reservation',
            name='room',
            field=models.ManyToManyField(to='room.Room'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bill',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='room.Room'),
        ),
        migrations.AddField(
            model_name='bill',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
