# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-02 11:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='reservation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='room.Reservation'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bill',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='bill',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='room',
        ),
        migrations.AddField(
            model_name='reservation',
            name='room',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='room.Room'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reservation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='room',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='room',
            name='size',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
